export const estrela = require('./estrela.png')
export const estrelaCinza = require('./estrelaCinza.png')
export const logo = require('./logo.png')

// export const grow = require('./produtores/grow.png')
// export const green = require('./produtores/green.png')
// export const jennyJack = require('./produtores/jenny-jack.png')
// export const potager = require('./produtores/potager.png')
// export const salad = require('./produtores/salad.png')

export const grow = require('./estrela.png')
export const green = require('./estrela.png')
export const jennyJack = require('./estrela.png')
export const potager = require('./estrela.png')
export const salad = require('./estrela.png')